version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./.db/data:/var/lib/postgresql/data

  localstack:
    container_name: aws-localstack
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=sqs,s3
      - SQS_PROVIDER=elasticmq
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./.data/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.localstack-initials:/docker-entrypoint-initaws.d/

  server:
    container_name: consumer
    build:
      target: development
      context: ./cb-consumer
      dockerfile: .docker/dockerfile
    volumes:
      - ./cb-consumer/src:/usr/consumer/src
      - ./cb-consumer/package.json:/usr/consumer/package.json
      - ./cb-consumer/node_modules:/usr/consumer/node_modules
    env_file:
      - ./cb-consumer/.env
